Sqlite crud functionalities
amilajack/falcon-core-old pull request #18
Opened 2017-07-20 20:05 UTC by jooohhn

## Features
- Added support for row deletion
- Added support for row updates
- Added support for row insertion
- Added `getPrimaryKey(table)` 
- Added tests for deletion, update, and insertion

2017-07-20 22:26 UTC, jooohhn commented on package.json
> +    "lint-fix": "prettier --single-quote --write \"{,!(flow-typed|lib)/**}/*.{js,jsx}\" && yarn lint -- --fix",
Added this line for quick lint fixing

2017-07-20 22:28 UTC, amilajack commented on package.json
> +    "lint-fix": "prettier --single-quote --write \"{,!(flow-typed|lib)/**}/*.{js,jsx}\" && yarn lint -- --fix",
Yup, saw this. 👍 for this

2017-07-20 22:30 UTC, jooohhn commented on src/db/provider_clients/ProviderInterface.js
> -  getTableKeys: (table: string) => Promise<Array<{
- Adjusted `getTableKeys()` to return data about table columns
- `getPrimaryKey()` returns the unique primary key for a row

2017-07-20 22:31 UTC, jooohhn commented on src/db/provider_clients/ProviderInterface.js
>     */
CRUD didn't seem to fit semantically because I thought delete, insert, and update are more intuitive with sqlite syntax

2017-07-20 22:32 UTC, jooohhn commented on src/db/provider_clients/SqliteProviderFactory.js
Added implementation for insert, delete, update.

2017-07-20 22:34 UTC, jooohhn reviewed
These are the new tests for SQLite's delete, insert, and update

2017-07-20 22:34 UTC, jooohhn commented on test/Databases.spec.js
Added CRUD method tests for sqlite

2017-07-20 22:50 UTC, amilajack requested changes

2017-07-20 22:50 UTC, amilajack commented on test/Databases.spec.js
> +              await dbConn.insert('users');
Shouldn't `insert()` take an argument of the object to insert?

2017-07-20 22:50 UTC, amilajack commented on test/Databases.spec.js
> +              expect(usersValuesBefore[0]).toEqual({
Make sure that all the new tests that use `.toEqual()` have their snapshot taken for every test

2017-07-20 23:07 UTC, jooohhn commented on test/Databases.spec.js
> +              expect(usersValuesBefore[0]).toEqual({
Got this

2017-07-20 23:10 UTC, jooohhn commented on test/Databases.spec.js
> +              await dbConn.insert('users');
You're right. Now that I think about it my original idea seems wrong.

2017-07-20 23:12 UTC, amilajack commented on test/Databases.spec.js
> +              await dbConn.insert('users');
I would recommend taking a look at the API's of ORM's like sequalize

2017-07-20 23:21 UTC, amilajack requested changes

2017-07-20 23:21 UTC, amilajack commented on src/db/provider_clients/ProviderInterface.js
> +  delete: (table: string, keys: Array<string>) => Promise<bool>,
Should these methods be changed back to the original lines (140 - 143)?

2017-07-20 23:32 UTC, jooohhn commented on src/db/provider_clients/ProviderInterface.js
> +  delete: (table: string, keys: Array<string>) => Promise<bool>,
Did you want to remove the original CRUD methods and replace them with insert, delete, udpdate?

2017-07-20 23:36 UTC, amilajack requested changes

2017-07-20 23:36 UTC, amilajack commented on src/db/provider_clients/SqliteProviderFactory.js
> +    if (values === null || values === undefined) {
Prefer `!values` instead of strict checks

2017-07-20 23:36 UTC, amilajack commented on src/db/provider_clients/SqliteProviderFactory.js
> +      return results;
Returning the result of an `await` is somewhat verbose. Can reduce this to:

```js
return this.driverExecuteQuery({ query }).then(res => res.data)
```

2017-07-20 23:36 UTC, amilajack commented on src/db/provider_clients/SqliteProviderFactory.js
> +    INSERT INTO ${table} (${columns.join(', ')})
add two spaces to this line and one below

2017-07-20 23:38 UTC, amilajack commented on src/db/provider_clients/ProviderInterface.js
> +  delete: (table: string, keys: Array<string>) => Promise<bool>,
I think we should keep [these methods and their signatures](https://github.com/falcon-client/falcon-core/blob/master/src/db/provider_clients/ProviderInterface.js#L117-L125). Do you agree with signatures of those methods?

2017-07-20 23:51 UTC, jooohhn commented on src/db/provider_clients/SqliteProviderFactory.js
> +      return results;
Added in commit 106f6d1

2017-07-20 23:56 UTC, jooohhn commented on src/db/provider_clients/ProviderInterface.js
> +  delete: (table: string, keys: Array<string>) => Promise<bool>,
- `create: (table: string, objectToInsert: Object) => Promise<bool>,`
I think it's a little ambiguous. Doesn't differentiate between creating a new row/record vs creating a new table
- `read: (table: string, objectToInsert: Object) => Promise<bool>,`
Do we need this if we already have methods that get us the contents of a table?
- `update: (table: string, objectToInsert: Object) => Promise<bool>,`
Not too bad
- `delete: (table: string, objectToInsert: Object) => Promise<bool>,`
Not sure what we'd be inserting if we're deleting.
- Also these signatures seem to only deal with CRUDing 1 record at a time

2017-07-20 23:59 UTC, amilajack commented on src/db/provider_clients/ProviderInterface.js
> +  delete: (table: string, keys: Array<string>) => Promise<bool>,
Good insight. Let's hold off on changing create/read for now. Update and delete are what we really need. `delete` should actually take an array of primary keys of reach record that is to be deleted.

2017-07-21 00:08 UTC, jooohhn commented on src/db/provider_clients/ProviderInterface.js
> +  delete: (table: string, keys: Array<string>) => Promise<bool>,
Alright did you want to keep the old nomenclature or use mine?

2017-07-21 00:08 UTC, amilajack commented on src/db/provider_clients/ProviderInterface.js
> +  delete: (table: string, keys: Array<string>) => Promise<bool>,
Up to you

2017-07-27 00:41 UTC, jooohhn commented
Closes #17

2017-07-27 00:42 UTC, merged

2017-07-27 00:43 UTC, amilajack commented
Yeeeee 🎉 🎉 🎉 🎉